kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-demo
spec:
  storageClassName: regionalpd-storageclass
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
